// 发布前验证（10.9）：ComfyUI 图像生成链路四层齐全
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');

let pass = 0, fail = 0;
function check(name, cond) {
  if (cond) { pass++; console.log('PASS ' + name); }
  else { fail++; console.log('FAIL ' + name); }
}

const server = read('server.js');
const app = read('public/app.js');
const mcp = read('phone-mcp.js');
const java = read('android/src/com/local/codexbridge/MainActivity.java');
const cfg = read('config.example.json');

const wfDir = path.join(root, 'comfy-workflows');
const direct = JSON.parse(fs.readFileSync(path.join(wfDir, 'zimage_direct_api.json'), 'utf8'));
const upscale = JSON.parse(fs.readFileSync(path.join(wfDir, 'zimage_upscale_api.json'), 'utf8'));
const gpt = JSON.parse(fs.readFileSync(path.join(wfDir, 'gptimage2_api.json'), 'utf8'));

check('zimage 直出文件有 CLIPTextEncode+KSampler+SaveImage', direct['27'] && direct['27'].class_type === 'CLIPTextEncode' && direct['3'] && direct['3'].class_type === 'KSampler' && direct['999'] && direct['999'].class_type === 'SaveImage');
check('zimage 超分文件有超分链+SaveImage', upscale['76'] && upscale['76'].class_type === 'ImageUpscaleWithModel' && upscale['77'] && upscale['999']);
check('gptimage2 文件有 LoadImage+GPT+SaveImage', gpt['299'] && gpt['300'] && gpt['300'].class_type === 'OpenAIGPTImage1' && gpt['999']);
check('三个文件 SaveImage 都带 filename_prefix', direct['999'].inputs.filename_prefix && upscale['999'].inputs.filename_prefix && gpt['999'].inputs.filename_prefix);
check('zimage 用展开后的真实管线节点', direct['30'] && direct['30'].class_type === 'CLIPLoader' && direct['8'] && direct['8'].class_type === 'VAEDecode');
check('server 有 comfyGenerate', server.includes('async function comfyGenerate('));
check('server 有工作流映射', server.includes('zimage_direct_api.json') && server.includes('gptimage2_api.json'));
check('server 能力开关校验', server.includes('图像生成未开启，请先在手机设置里开启'));
check('server 无图纯文生图（删 LoadImage）', server.includes("delete graph['299']") && server.includes("delete graph['300'].inputs.image"));
check('server 进度广播 comfyProgress', server.includes("method: 'comfyProgress'"));
check('server 广播 comfyStarted', server.includes("method: 'comfyStarted'"));
check('server 支持 comfyApiKey 透传', server.includes('extraData.api_key_comfy_org = config.comfyApiKey') && server.includes('extra_data: extraData'));
check('server 支持 Firebase 令牌自动续期', server.includes('function getComfyAuthToken()') && server.includes('securetoken.googleapis.com') && server.includes('comfyFirebaseRefreshToken'));
check('server 未启动可读提示', server.includes('请先在电脑上启动 ComfyUI'));
check('server 有 HTTP 端点', server.includes("'/api/comfy/generate'"));
check('app.js 处理 comfyProgress', app.includes("method === 'comfyProgress'") && app.includes('updateComfyProgress'));
check('app.js 处理 comfyStarted', app.includes("method === 'comfyStarted'") && app.includes('startComfyProgress(params.promptId)'));
check('app.js 有生成卡片计时', app.includes('生成中 ') && app.includes('rec.timer = setInterval'));
check('app.js 上报能力', app.includes('function reportCapabilities()') && app.includes("'reportCapabilities'"));
check('app.js lanCall 支持能力上报', app.includes("case 'reportCapabilities'"));
check('app.js 渲染 AI 图片+保存按钮', app.includes('renderAgentTextWithImages') && app.includes('img-save-btn') && app.includes('saveImageToDevice'));
check('app.js 无自动存相册', !app.includes('autoSaveComfyImage') && !app.includes('data-auto'));
check('app.js 生成图缓存到 App', app.includes('cacheGeneratedImage') && app.includes('loadComfyImgCache') && app.includes('data-comfy') && app.includes('cacheImageToApp'));
check('app.js 中继取图 dataURL', app.includes('fetchComfyDataUrl'));
check('server 有上报 HTTP 端点', server.includes("'/api/report-capabilities'"));
check('能力缓存持久化', server.includes('PHONE_CAPS_PATH') && server.includes('loadPhoneCaps()'));
check('server 有删除图片接口', server.includes('deleteComfyImage') && server.includes("'/api/images/delete'"));
check('server 有中继取图接口', server.includes('comfyImageDataUrl') && server.includes("'/api/comfy-image'"));
check('server 有 30 分钟兜底清理', server.includes('function cleanupComfyImages') && server.includes('30 * 60 * 1000'));
check('server 图片服务前缀匹配', server.includes("p.startsWith('/uploads/')") && server.includes("path.basename(p)"));
check('MCP 有 generate_image', mcp.includes("name: 'generate_image'"));
check('MCP 默认 gptimage2', mcp.includes("args.workflow || 'gptimage2'"));
check('MCP 描述强调默认 gptimage2', mcp.includes('除非用户明确要求使用本地 z-image 生成'));
check('server 默认 gptimage2', server.includes("params.workflow || 'gptimage2'"));
check('server gptimage2 直连 OpenAI', server.includes('async function openaiGenerate(') && server.includes('api.openai.com/v1/images/generations') && server.includes('api.openai.com/v1/images/edits') && server.includes('config.imageProvider === \'openai\''));
check('server 默认 comfy 通道', server.includes("imageProvider: 'comfy'") && server.includes("merged.imageProvider !== 'openai'"));
check('server 挂 undici 代理', server.includes("require('undici')") && server.includes('ProxyAgent') && server.includes('httpsProxy'));
check('server 刷新失败回退临时令牌', server.includes('回退使用临时 comfyAuthToken'));
check('server 读取 openaiApiKey', server.includes("config.openaiApiKey || process.env.OPENAI_API_KEY"));
check('server 错误翻译完整', server.includes('OpenAI API Key 无效或未授权') && server.includes('OpenAI 限流或额度不足'));
check('server 尺寸默认横图 1536x1024', server.includes("return '1536x1024'"));
check('MainActivity 有图像生成开关', java.includes('KEY_CAP_IMAGE_GEN') && java.includes('图像生成（ComfyUI'));
check('config.example 有 comfyUrl', cfg.includes('comfyUrl'));
check('config.example 有 comfyApiKey', cfg.includes('comfyApiKey'));
check('config.example 有 comfyFirebaseRefreshToken', cfg.includes('comfyFirebaseRefreshToken'));
check('config.example 有 openaiApiKey', cfg.includes('openaiApiKey'));
check('config.example 有 httpsProxy', cfg.includes('httpsProxy'));
check('.gitignore 忽略 node_modules', read('.gitignore').includes('node_modules/'));
check('Java 有保存到相册方法', java.includes('saveImageToGallery') && java.includes('MediaStore.Images.Media'));
check('Java 有 App 内缓存方法', java.includes('cacheImageToApp') && java.includes('files.length > 10'));
check('Manifest 有低版本存储权限', read('android/AndroidManifest.xml').includes('WRITE_EXTERNAL_STORAGE'));
const css = read('public/style.css');
const html = read('public/index.html');
const relay = read('public/relay.js');
check('占位卡固定高度 180px', app.includes('width="320" height="200"') && css.includes('height: 180px'));
check('卡片内联样式兜底', app.includes('min-height:180px;') && app.includes("ph.style.cssText"));
check('图片描述标签替代感叹号', app.includes('agent-img-tag') && app.includes("replace(/^!/, '')"));
check('style 有图片描述标签', css.includes('.agent-img-tag'));
check('查看器返回键接管', app.includes('history.pushState({ viewer: true }') && app.includes("addEventListener('popstate'"));
check('纯图片消息不朗读', app.includes('updateSpeakBtnVisibility') && app.includes("clone.querySelectorAll('.agent-img')") && app.includes("spk.classList.toggle('hidden'"));
check('文件消息不朗读', app.includes("clone.querySelectorAll('.agent-file').forEach(n => n.remove())") && app.includes('文件不参与朗读'));
check('图片失败兜底+重试', app.includes('img-fail-note') && app.includes('img-retry-btn') && app.includes('img-broken'));
check('回合超时点此刷新', app.includes('scheduleTurnFallback') && app.includes('turnFallbackReload'));
check('lanCall 超时控制', app.includes('AbortController') && app.includes('请求超时'));
check('style 图片占位与失败样式', css.includes('.img-fail-note') && css.includes('min-height: 180px') && css.includes('.img-broken'));
check('卡片最短可见 1.5 秒', app.includes('1500 - (Date.now() - rec.startTs)'));
check('多卡片队列', app.includes('comfyCards') && app.includes('排队中') && app.includes('promoteNextComfyCard'));
check('纸张堆叠容器', app.includes('comfyStackEl') && app.includes('ensureComfyStack') && app.includes('reflowComfyStack') && css.includes('.comfy-stack'));
check('堆叠层叠偏移', app.includes("left = (slot * 8) + 'px'") && app.includes('let nonTopSlot = top ? 1 : 0'));
check('下层不透明+边框阴影分层', app.includes("rec.card.style.opacity = '1'") && app.includes('borderColor') && app.includes('boxShadow') && app.includes("badge.style.display = isTop ? '' : 'none'"));
check('预创建：解析数量词', app.includes('function parseChineseNum(') && app.includes('张|个|种|版|套') && app.includes('Math.min(n, 9)') && app.includes("state: i === 0 ? 'generating' : 'queued'"));
check('预创建：发送时立即建叠', app.includes('parseImageCount(sendText)') && app.includes("if (preCount >= 2) precreateComfyStack(preCount)"));
check('预创建池绑定', app.includes('function bindComfyCard(') && app.includes('!rec.bound') && app.includes('function comfyFind('));
check('对比对象数推断', app.includes('tokens.length >= 2') && app.includes('listPart.split(/和|与|、|,|，') && app.includes('s.split(/分别/).pop()') && app.includes('多图暗示词兜底'));
check('串行完成保留堆叠（下沉不移除）', app.includes('function completeComfyCard(') && app.includes("rec.state = 'done'") && app.includes("rec.card.style.left = '8px'") && app.includes('setTimeout(finishState, 520)'));
check('上浮连续动效', app.includes("translate(0, 6px) scale(0.97)") && app.includes('next.rising = true') && app.includes('rec.card.style.zIndex = isTop ? String(recs.length + 1)'));
check('回合结束清理残留卡', app.includes('function clearComfyCards()') && app.includes('clearComfyCards(); // 回合结束'));
check('真实 promptId 改绑 tool 卡', app.includes("String(rec.promptId || '').indexOf('tool-') === 0") && app.includes("if (!String(id).startsWith('tool-'))"));
check('工具兜底仅在无未绑定卡时建卡', app.includes('const hasUnbound = [...comfyCards.values()].some(r => !r.bound)') && app.includes("startComfyProgress('tool-' + item.id)"));
check('切对话不清进度卡', !app.includes('async function openThread(id) {\n    finishComfyProgress();') && app.includes('async function openThread(id) {'));
check('堆叠容器回到消息流内', app.includes('(messagesEl || document.body).appendChild(comfyStackEl)') && app.includes('function clearMessagesPreserveComfyStack()'));
check('清空消息区保留堆叠并重挂', app.includes('clearMessagesPreserveComfyStack();') && app.includes('messagesEl.innerHTML = \'\';'));
check('历史渲染后兜底重挂堆叠', app.includes('function restoreComfyStackIfNeeded()') && app.includes('parentNode.lastChild !== comfyStackEl'));
check('堆叠容器样式回到消息流内', css.includes('order: 9999') && css.includes('margin-top: auto') && css.includes('margin: 4px 0 12px'));
check('兼容本地链接图片格式', app.includes("[^)]*\\/uploads\\/[^)]+"));
check('app 内置全屏查看器', app.includes('openImageViewerOverlay') && app.includes('viewerScale') && app.includes("('ontouchstart' in window)"));
check('style 有查看器遮罩', css.includes('.viewer-overlay') && css.includes('touch-action: none'));
check('app comfy 事件诊断日志', app.includes("console.log('[event] ' + method)") || app.includes('/^comfy/.test(method)'));
check('事件日志只显示 comfy', app.includes("String(name || '').indexOf('comfy') !== 0"));
check('卡片双保险：工具调用即显示', app.includes('/generate_image/i.test'));
check('gptimage2 事件带 promptId', server.includes("method: 'comfyDone', params: { promptId }") && server.includes("method: 'comfyError', params: { promptId, error"));
check('server 有 health', server.includes("'/api/health'"));
check('server 有慢请求日志', server.includes("[slow] ' + req.method"));
check('server 有 turn 看门狗 90 秒', server.includes('turn/failed') && server.includes('90 * 1000') && server.includes('15000'));
check('server 事件循环看门狗', server.includes('lastHeartbeatAt') && server.includes('gap > 30000') && server.includes('process.exit(1)'));
check('server idle 诊断日志', server.includes('[idle] turn') && server.includes('lastCodexOutputAt') && server.includes('30000'));
check('前端自动重启恢复', app.includes('function startAutoRecovery()') && app.includes('电脑端无响应，正在自动重启') && app.includes('function handleUnresponsive(') && app.includes("fetch('/api/health', { cache: 'no-store', signal: ctl.signal })"));
check('TTS 超时缩至 90 秒', server.includes('ttsTimeoutMs: 90000') && server.includes('90 * 1000') && !server.includes('12 * 60 * 1000'));
check('TTS 繁忙/超时错误翻译', server.includes('语音服务繁忙，请稍后重试') && server.includes('语音生成超时') && server.includes('r.status === 409') && server.includes('r.status === 504'));
check('网页朗读实时优先', server.includes("cancelPreGen(); // 网页朗读同样是实时请求"));
check('局域网流式补 4 字节长度头', server.includes('head.writeUInt32LE(frame.length, 0)') && server.includes('Buffer.concat([head, frame])') && server.includes('与前端 consumeLanTtsStream 协议对齐'));
check('前端全链路重连', app.includes('function reconnectAll()') && app.includes('reconnectThreadBtn'));
check('Java 有图片查看器', java.includes('openImageViewer') && java.includes('LocalFileProvider.AUTHORITY'));
check('Manifest 注册本地 Provider', read('android/AndroidManifest.xml').includes('LocalFileProvider'));
check('LocalFileProvider 文件存在', fs.existsSync(path.join(root, 'android/src/com/local/codexbridge/LocalFileProvider.java')));
check('输入框分隔线已调暗', css.includes('rgba(0, 210, 160, 0.07)'));
check('style.css 有占位卡片样式', css.includes('.comfy-generating') && css.includes('.comfy-placeholder') && css.includes('.comfy-badge') && css.includes('comfy-breathe'));
check('输入框加号+附件菜单', html.includes('id="attachBtn"') && html.includes('＋') && html.includes('id="attachMenu"'));
check('文件选择 input 白名单', html.includes('id="fileInput"') && html.includes('accept=".txt,.md'));
check('app 有 pendingFiles', app.includes('pendingFiles: []'));
check('app 文件大小限制', app.includes('MAX_FILE_BYTES') && app.includes('RELAY_MAX_FILE_BYTES'));
check('app 发送带 files', app.includes('files: files.map(f => ({ name: f.name, data: f.data }))'));
check('app 文件类型校验', app.includes('TEXT_FILE_EXTS.includes(ext)') && app.includes('不支持的文件类型'));
check('app 文件预览 chips', app.includes('file-chip') && app.includes('formatBytes'));
check('style 附件菜单与文件 chips', css.includes('.attach-menu') && css.includes('.file-chip') && css.includes('.file-chip-msg'));
check('server 处理 body.files', server.includes('(body.files || [])') && server.includes('saveUploadFile(f.data, f.name)'));
check('server 文本读取传入 codex', server.includes('readUploadedText(file)') && server.includes("【附件：' + label + '】"));
check('server 附件白名单/大小/清理', server.includes('TEXT_FILE_EXTS') && server.includes('MAX_FILE_BYTES') && server.includes("name.startsWith('upload-')"));
check('lanCall 发送带 files', app.includes("files: params.files || []"));
check('server 上传 MIME 覆盖文档', server.includes("'.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'") && server.includes("'.pptx'") && server.includes("'.pdf': 'application/pdf'"));
check('server 文件下载头 RFC5987', server.includes("filename*=UTF-8''") && server.includes("attachment; filename"));
check('server 有文件发布接口', server.includes("'/api/file/publish'") && server.includes("case 'filePublish':"));
check('server 发布白名单/大小/pub- 前缀', server.includes('PUB_FILE_EXTS') && server.includes('MAX_PUB_FILE_BYTES') && server.includes("'pub-' + id + ext"));
check('server 发布仅限工作目录/uploads', server.includes('仅支持发布工作目录或 uploads 内的文件'));
check('MCP 有 publish_file 工具', mcp.includes("name: 'publish_file'") && mcp.includes("'/api/file/publish'"));
check('MCP publish_file 描述带下载语法', mcp.includes('📄 [文件名](返回的url)'));
check('app 渲染文件下载卡片', app.includes('agent-file') && app.includes('agent-file-btn') && app.includes('downloadAgentFile'));
check('app 中继分片下载流程', app.includes('function relayDownloadFile(') && app.includes('正在传输文件到手机…') && app.includes("apiCall('fileData'"));
check('app 分片并发拉取', app.includes('Math.min(4, meta.chunks)') && app.includes("index: idx") && app.includes('60000'));
check('app 中继保存用 dataURL', app.includes("saveFileToPhone(dataUrl"));
check('app 中继失败明确报错', app.includes("分片 ' + (idx + 1) + ' 获取失败") && app.includes('下载失败: '));
check('app 调用原生保存文件', app.includes('saveFileToPhone'));
check('style 有文件下载卡片', css.includes('.agent-file') && css.includes('.agent-file-btn'));
check('Java 有保存文件方法', java.includes('saveFileToPhone') && java.includes('getFilesDir(), "downloads"'));
check('Java 下载带登录 Cookie', java.includes('CookieManager.getInstance()') && java.includes('c.setRequestProperty("Cookie", cookie)') && java.includes('未授权（请重新登录电脑端）'));
check('前端去重错误前缀', app.includes("indexOf('下载失败:') === 0") && app.includes("indexOf('保存失败:') === 0"));
check('AI 行为规范要求发布文件', server.includes('publish_file 工具') && server.includes('📄 [文件名](链接)'));
check('server 有中继文件分片接口', server.includes("case 'fileData':") && server.includes('function safePubPath(') && server.includes('FILE_DATA_CHUNK'));
check('server 分片只允许 pub-*', server.includes('pub-[A-Za-z0-9._-]+') && server.includes('仅支持 /uploads/pub-*'));
check('server 分片兼容完整 URL', server.includes('https?:\\/\\/[^/]+') && server.includes('(pub-[A-Za-z0-9._-]+)$'));
check('server 分片返回元信息', server.includes('params.meta') && server.includes('chunks: total') && server.includes('chunkBytes'));
check('server 分片读取 base64', server.includes('buf.toString(\'base64\')') && server.includes('fs.readSync'));
check('server 文件数据 HTTP 端点', server.includes("'/api/file/data'"));
check('app 下载状态持久化', app.includes('downloadedFiles') && app.includes('function isFileDownloaded(') && app.includes('function markFileDownloaded(') && app.includes('function setFileBtnOpen('));
check('app 下载成功按钮变打开', app.includes("agent-file-btn' + (opened ? ' open' : '')") && app.includes("(opened ? '打开' : '下载')"));
check('app 点击打开已下载文件', app.includes("fbtn.classList.contains('open')") && app.includes('function openAgentFile(') && app.includes('AndroidBridge.openFile'));
check('style 打开按钮高亮', css.includes('.agent-file-btn.open'));
check('Java 有 openFile 方法', java.includes('public String openFile(') && java.includes('LocalFileProvider.AUTHORITY') && java.includes('Intent.createChooser'));
check('Java 保存到公共 Downloads', java.includes('MediaStore.Downloads') && java.includes('DIRECTORY_DOWNLOADS') && java.includes('getExternalStoragePublicDirectory'));
check('LocalFileProvider 服务下载目录', read('android/src/com/local/codexbridge/LocalFileProvider.java').includes('"downloads/" + name') && read('android/src/com/local/codexbridge/LocalFileProvider.java').includes('MimeTypeMap'));
check('server 系统要求独立常量', server.includes('const SYSTEM_REQUIREMENT =') && server.includes('publish_file 工具'));
check('server 用户消息只存原文', server.includes("if (userText) input.push({ type: 'text', text: userText })") && !server.includes('promptText = userText'));
check('server 历史剥离系统要求', server.includes('function cleanThreadHistory(') && server.includes('SYSTEM_REQUIREMENT.trim()') && server.includes('\\[系统要求：[\\s\\S]*\\]'));
check('前端过滤历史系统要求', app.includes('\\[系统要求：[\\s\\S]*\\]') && app.includes('兜底：历史里混入的系统要求不再显示'));
check('前端用户气泡兜底过滤', app.includes('兜底：不把系统要求显示在用户气泡里'));
check('app 自动朗读等预生成缓存', app.includes('function waitTtsStatus(') && app.includes('setTimeout(tick, 500)') && app.includes('waitTtsStatus(clean, ttsTimeoutFor(clean, 30000))'));
check('app 流式超时按长度放宽', app.includes('setTimeout(() => ctl.abort(), ttsTimeoutFor(streamText, 30000))') && app.includes('signal: ctl.signal'));
check('app 流式失败等缓存再降级', app.includes('waitTtsStatus(streamText, Math.min(ttsTimeoutFor(streamText, 30000), 60000))') && app.includes('playMessageSegments(convId, msgId, streamText, auto, temp)'));
check('app 单回合生图上限', app.includes('let turnGenCount = 0') && app.includes('turnGenCount++') && app.includes('检测到多次生图请求'));
check('server 用户文本剥离系统提示段', server.includes("String(body.text || '').replace") && server.includes('\\[系统要求：[\\s\\S]*?\\]'));
check('server 自动朗读也预生成', server.includes('if (text) queuePreGen(text, auto)'));
check('server TTS 请求日志', server.includes("[tts] /api/tts/stream") && server.includes("[tts] ttsStatus") && server.includes('[tts] /api/tts 耗时'));
check('MCP 生图意图闸门', mcp.includes('只有用户明确要求出图') && mcp.includes('Word/PPT/PDF/Excel/文档/文件/表格/文本时禁止调用') && mcp.includes('粘贴的更新日志'));
check('MCP 生图展示模板固定', mcp.includes('[描述](返回的url)') && mcp.includes('禁止使用 ![描述](url)'));
check('server 一键配置下发通道与能力', server.includes("imageProvider: config.imageProvider || 'comfy'") && server.includes('device_status: !!') && server.includes('image_generation: !!'));
check('Java applyConfig 恢复能力开关', java.includes('public void applyConfig(String json)') && java.includes('KEY_CAP_DEVICE_STATUS') && java.includes('KEY_CAP_IMAGE_GEN'));
check('app 一键配置恢复能力开关', app.includes('window.AndroidBridge.applyConfig') && app.includes('cfg.caps'));
check('server 洗图/超分工作流映射', server.includes("wash: 'flux2_wash_api.json'") && server.includes("upscale: 'flux2_upscale_api.json'"));
check('洗图/超分工作流文件存在', fs.existsSync(path.join(root, 'comfy-workflows/flux2_wash_api.json')) && fs.existsSync(path.join(root, 'comfy-workflows/flux2_upscale_api.json')) && fs.existsSync(path.join(root, 'comfy-workflows/flux2_wash_upscale_backup.json')));
check('工作流 SaveImage 前缀 codex_', read('comfy-workflows/flux2_wash_api.json').includes('codex_wash') && read('comfy-workflows/flux2_upscale_api.json').includes('codex_upscale'));
check('server inputTemp 先声明后使用', (() => { const d = server.indexOf('let inputTemp = null;'); return d >= 0 && d < server.indexOf('inputTemp = { dir: inputDir'); })());
check('server 清理 ComfyUI output', server.includes('function cleanupComfyOutput(') && server.includes("n.startsWith('codex_')") && server.includes('setInterval(cleanupComfyOutput, 60 * 60 * 1000)'));
check('MCP 洗图/超分选项', mcp.includes("'wash', 'upscale'") && mcp.includes('洗图') && mcp.includes('超分') && mcp.includes('必须传 imagePath'));
check('app 询问词不预创建卡片', app.includes('询问/引用类表述不预创建卡片') && app.includes('什么|区别|怎么|为什么'));
check('server TTS 全局门锁', server.includes('function ttsGateRun(') && server.includes('ttsGateRun(() => fetch'));
check('server TTS 409 自动重试', server.includes('attempt >= 30') && server.includes('setTimeout(res, 2000)') && server.includes('r.status === 409'));
check('app 发送时取消自动朗读补试', app.includes('clearTimeout(autoSpeakRetryTimer); // 取消待定的自动朗读补试') && app.includes('autoSpokenMsgKey = null; // 发送新消息后'));
check('app 自动朗读跳过含生图消息', app.includes('最新消息含生图，等待图片完成') && app.includes('.agent-img img[data-comfy="1"]'));
check('server 朗读与本地生图串行调度', server.includes('localGenBusy') && server.includes('function waitLocalGenFree(') && server.includes('function waitTtsFree(') && server.includes('语音未结束不启动本地生图'));
check('server ComfyUI input 目录优先', server.includes("path.join('E:', 'ComfyUI', 'resources', 'ComfyUI', 'input')") && server.indexOf("resources', 'ComfyUI', 'input')") < server.indexOf("NewComfyUi', 'input')"));
check('server TTS 等待本地生图', server.includes('ttsGate.then(async () => { await waitLocalGenFree(); return fn(); }'));
check('app 整轮生图期间延迟朗读', app.includes('liveGenRunning') && app.includes('本回合生图进行中，等生图完成再朗读'));
check('app 手动朗读生图时排队', app.includes('pendingManualSpeak') && app.includes('生图进行中，稍后朗读') && app.includes('function maybePlayPendingManualSpeak('));
check('app 保存图片优先本地缓存', app.includes('function comfyLocalPath(') && app.includes('优先使用手机本地缓存') && app.includes('const local = comfyLocalPath(url)') && app.includes("'file://' + String(p).replace(/\\\\/g, '/')"));
check('app 生成语音服务总开关', app.includes('let ttsEnabled = true') && app.includes('function readTtsEnabledPref(') && app.includes('function refreshTtsPrefs(') && app.includes('生成语音服务已关闭'));
check('app 语音关闭时按钮隐藏与手动拦截', app.includes('!hasText || !ttsEnabled') && app.includes('语音服务已关闭，请在设置里开启'));
check('Java 生成语音服务开关', java.includes('KEY_TTS_ENABLED') && java.includes('public boolean getTtsEnabled()') && java.includes('生成语音服务（关闭后所有语音都不生成，自动朗读一起关）'));
check('Java 设置表单可滚动+联动关闭', java.includes('new android.widget.ScrollView(this)') && java.includes('if (!ttsEnabled) autoSpeak = false;') && java.includes('autoSpeakBox.setChecked(false)'));
check('中继分片重组超时自适应', relay.includes('Math.min(120000, 10000 + Math.ceil(entry.total / 20) * 10000)'));
check('中继分片缺失补拉', relay.includes("type === 'relay-resend'") && relay.includes('_handleResend(req)') && relay.includes('_maybeResend(entry, env.c)'));
check('中继发送端保留分片供补拉', relay.includes('_sentChunks') && relay.includes('rec.timer = setTimeout'));
check('中继图片渲染后主动取图', app.includes('block.querySelectorAll(\'.agent-img img[data-comfy="1"]\')') && app.includes('setTimeout(function () { resolveComfyImg(im); }, 120)'));
check('autoSpeak 跳过诊断日志', app.includes("[autoSpeak] 跳过:") && app.includes('[autoSpeak] 跳过: 没有 AI 消息') && app.includes('[autoSpeak] 跳过: 本轮没有新回复'));
check('autoSpeak 回合基线双向设置', (app.match(/turnStartLastMsgId = currentLastMsgId\(\);/g) || []).length >= 2);
check('多次生图确认弹窗', app.includes('function showConfirmDialog(') && app.includes('是否确认继续生成') && app.includes('genConfirmApproved'));
check('style 确认弹窗样式', css.includes('.confirm-dialog') && css.includes('.confirm-box'));
check('授权弹窗内容可滚动按钮固定', app.includes('class="a-body"') && css.includes('.approval-card .a-body') && css.includes('overflow-y: auto') && css.includes('max-height: 82vh') && css.includes('flex: 0 0 auto'));
check('server 发布文件数量上限', server.includes('function prunePubFiles(') && server.includes('prunePubFiles(10)') && server.includes("n.startsWith('pub-')"));
check('Java 下载缓存清理', java.includes('pruneDownloadsCache') && java.includes('files.length - 10'));
check('Java 过期文件友好提示', java.includes('文件已被清理或已过期，请重新下载'));
check('app 下载标记按 100 条清理', app.includes('while (arr.length > 100) arr.shift()'));
check('app 图片映射按 100 条清理', app.includes('entries.length > 100') && app.includes('Object.fromEntries'));
check('app 删除对话清理本地语音记录', app.includes('function clearConvLocalData(') && app.includes('clearConvLocalData(threadId)'));
check('server 自动会话清理', server.includes('function pruneOldThreads(') && server.includes('autoCleanThreads') && server.includes('threadRetentionDays') && server.includes('threadRetentionCount') && server.includes('24 * 60 * 60 * 1000'));
check('server 清理保留规则', server.includes('保护') && server.includes('slice(0, 10)') && server.includes("c.call('thread/delete', { threadId: t.id })"));
check('server 列表 limit 覆盖保留数量', server.includes('Math.max(200, Number(config.threadRetentionCount)'));
check('config.example 有会话保留配置', read('config.example.json').includes('autoCleanThreads') && read('config.example.json').includes('threadRetentionDays') && read('config.example.json').includes('threadRetentionCount'));
check('server 清理无前缀上传图', server.includes('noPrefixImg') && server.includes('[0-9a-f]{8,32}'));
check('server TTS 缓存体积上限', server.includes('超过 100MB') && server.includes('80 * 1024 * 1024'));
check('build-apk 先清空 android/build', read('build-apk.ps1').includes('Remove-Item -LiteralPath $build -Recurse -Force'));
check('Java 下载缓存 10 条上限', java.includes('pruneDownloadsCache') && java.includes('files.length <= 10'));
check('app 朗读超时按长度自适应', app.includes('function ttsTimeoutFor(') && app.includes('n * 1500 + 15000') && app.includes('Math.min(120000'));
check('app 流式用自适应超时', app.includes('ttsTimeoutFor(streamText, 30000)'));
check('app 长文本走分段合成', app.includes('clean.length > 30') && app.includes('playMessageSegments(convId, msgId, text, auto, temp)'));
check('app 自动朗读等缓存按长度放宽', app.includes('waitTtsStatus(clean, ttsTimeoutFor(clean, 30000))'));

console.log('Comfy 链路验证: ' + pass + ' 通过 / ' + fail + ' 失败');
process.exit(fail ? 1 : 0);
